trigger:
  branches:
    include:
      - main

variables:
  imageName: 'myapp-api'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: DockerInstaller@0
      displayName: Install Docker

    - task: Docker@2
      displayName: Build and Push Image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: Dockerfile
        containerRegistry: '<your-acr-service-connection>' # Created from Project Settings > Service Connections
        tags: |
          $(Build.BuildId)
